"""Offline-testable SEC N-PORT provider primitives."""

from .artifacts import SecArtifactRef, SecArtifactStore, SecReplaySession
from .batch import (
    AdvisoryLock,
    AppendOnlyIndex,
    Quarter,
    SecFundSelector,
    SecNportBatch,
    SecScheduledFundSelector,
    atomic_json,
    canonical_hash,
    canonical_json,
    enumerate_receipts,
    latest_completed_quarter,
    load_universe,
    partition_identity,
    publish_directory,
    quarter_range,
    store_immutable_payload,
)
from .core_dataset import (
    logical_table_hash,
    rows_from_result,
    validate_tables,
    write_partition,
    write_tables,
)
from .edgar import (
    SecPayloadReceipt,
    historical_basenames,
    historical_submission_url,
    parse_submissions,
    resolve_submissions,
)
from .edgartools_adapter import (
    SecFinancialsClient,
    ensure_edgar_available,
    parse_statement_rows,
    validate_user_agent,
)
from .endpoints import SecEdgarSubmissionsRequest, SecEmptyPolicy, SecNportQuarterRequest
from .financials import (
    SecCompanyFinancialVintage,
    SecFinancialsRequest,
    SecStatementRow,
    StatementType,
)
from .financials_dataset import (
    write_financials_partition,
)
from .http import SecHttpClient, SecHttpResponse, SecTransportEvidence, validate_sec_url
from .nport import (
    SecAvailabilityPolicy,
    SecFundHoldingVintage,
    SecHoldingVintageSet,
    SecNportQA,
    SecNportQuarterResult,
    SecNportScanCounts,
    SecUnavailableResult,
    enrich_vintages,
    extract_from_artifact,
    parse_sec_date,
    read_member,
)

__all__ = [
    "AdvisoryLock",
    "AppendOnlyIndex",
    "Quarter",
    "SecArtifactRef",
    "SecArtifactStore",
    "SecAvailabilityPolicy",
    "SecCompanyFinancialVintage",
    "SecEdgarSubmissionsRequest",
    "SecEmptyPolicy",
    "SecFinancialsClient",
    "SecFinancialsRequest",
    "SecFundHoldingVintage",
    "SecFundSelector",
    "SecHoldingVintageSet",
    "SecHttpClient",
    "SecHttpResponse",
    "SecNportBatch",
    "SecNportQA",
    "SecNportQuarterRequest",
    "SecNportQuarterResult",
    "SecNportScanCounts",
    "SecPayloadReceipt",
    "SecReplaySession",
    "SecScheduledFundSelector",
    "SecStatementRow",
    "SecTransportEvidence",
    "SecUnavailableResult",
    "StatementType",
    "atomic_json",
    "canonical_hash",
    "canonical_json",
    "enrich_vintages",
    "ensure_edgar_available",
    "enumerate_receipts",
    "extract_from_artifact",
    "historical_basenames",
    "historical_submission_url",
    "latest_completed_quarter",
    "load_universe",
    "logical_table_hash",
    "parse_sec_date",
    "parse_statement_rows",
    "parse_submissions",
    "partition_identity",
    "publish_directory",
    "quarter_range",
    "read_member",
    "resolve_submissions",
    "rows_from_result",
    "store_immutable_payload",
    "validate_sec_url",
    "validate_tables",
    "validate_user_agent",
    "write_financials_partition",
    "write_partition",
    "write_tables",
]
