"""Offline-testable SEC N-PORT provider primitives."""

from .artifacts import SecArtifactRef, SecArtifactStore, SecReplaySession
from .batch import (
    AdvisoryLock,
    AppendOnlyIndex,
    Quarter,
    SecEquityEtfUniverse,
    SecFundSelector,
    SecNportBatch,
    SecScheduledFundSelector,
    atomic_json,
    canonical_hash,
    canonical_json,
    enumerate_receipts,
    latest_completed_quarter,
    load_universe,
    partition_identity,
    publish_directory,
    quarter_range,
    store_immutable_payload,
)
from .core_dataset import (
    logical_table_hash,
    rows_from_result,
    validate_tables,
    write_partition,
    write_tables,
)
from .edgar import (
    SecPayloadReceipt,
    historical_basenames,
    historical_submission_url,
    parse_submissions,
    resolve_submissions,
)
from .edgartools_adapter import (
    SecFinancialsClient,
    SecFinancialsParseError,
    SecStatementParseError,
    ensure_edgar_available,
    parse_statement_rows,
    validate_user_agent,
)
from .endpoints import SecEdgarSubmissionsRequest, SecEmptyPolicy, SecNportQuarterRequest
from .financials import (
    SecCompanyFinancialVintage,
    SecFinancialsRequest,
    SecStatementRow,
    StatementType,
)
from .financials_dataset import (
    write_financials_partition,
)
from .http import SecHttpClient, SecHttpResponse, SecTransportEvidence, validate_sec_url
from .nport import (
    SecAvailabilityPolicy,
    SecFundHoldingVintage,
    SecHoldingVintageSet,
    SecNportQA,
    SecNportQuarterResult,
    SecNportScanCounts,
    SecUnavailableResult,
    enrich_vintages,
    extract_from_artifact,
    parse_sec_date,
    read_member,
)
from .pit import (
    SecConsumerCommit,
    SecNormalizedFinancialFactVersion,
    SecPitMode,
    SecPitPolicy,
    SecPitResult,
    SecQualityRecord,
    SecQualityStatus,
    select_sec_financial_versions,
    serialize_sec_typed_rows_projection,
)
from .pit_bundle import SecPitBundle, load_sec_pit_bundle, write_sec_pit_bundle
from .qualification import (
    Deadline,
    QualificationProgress,
    SecNportPartitionSet,
    SecNportPartitionSetEntry,
    SecNportQualificationRef,
    SecNportQualificationRequest,
    qualify_sec_nport,
    select_exact_partitions,
)
from .quality_findings import (
    SecMissingDataReason,
    SecQualityEvidenceRef,
    SecQualityFinding,
    SecQualityFindingStatus,
    SecQualityIssueClass,
    select_sec_quality_findings,
)
from .sgml_financials import (
    SecSgmlFinancialProduction,
    SecSgmlFinancialsRequest,
    produce_sec_financials_from_sgml,
)
from .structural_quality import SecStructuralQualityReport, evaluate_sec_structural_quality
from .xbrl_package import (
    SecXbrlPackage,
    SecXbrlPackageAvailability,
    SecXbrlPackageComponents,
    decode_sec_xbrl_package,
    serialize_sec_xbrl_package,
)
from .xbrl_package_financials import (
    SecXbrlPackageFinancialProduction,
    produce_sec_financials_from_xbrl_package,
)

__all__ = [
    "AdvisoryLock",
    "AppendOnlyIndex",
    "Deadline",
    "QualificationProgress",
    "Quarter",
    "SecArtifactRef",
    "SecArtifactStore",
    "SecAvailabilityPolicy",
    "SecCompanyFinancialVintage",
    "SecConsumerCommit",
    "SecEdgarSubmissionsRequest",
    "SecEmptyPolicy",
    "SecEquityEtfUniverse",
    "SecFinancialsClient",
    "SecFinancialsParseError",
    "SecFinancialsRequest",
    "SecFundHoldingVintage",
    "SecFundSelector",
    "SecHoldingVintageSet",
    "SecHttpClient",
    "SecHttpResponse",
    "SecMissingDataReason",
    "SecNormalizedFinancialFactVersion",
    "SecNportBatch",
    "SecNportPartitionSet",
    "SecNportPartitionSetEntry",
    "SecNportQA",
    "SecNportQualificationRef",
    "SecNportQualificationRequest",
    "SecNportQuarterRequest",
    "SecNportQuarterResult",
    "SecNportScanCounts",
    "SecPayloadReceipt",
    "SecPitBundle",
    "SecPitMode",
    "SecPitPolicy",
    "SecPitResult",
    "SecQualityEvidenceRef",
    "SecQualityFinding",
    "SecQualityFindingStatus",
    "SecQualityIssueClass",
    "SecQualityRecord",
    "SecQualityStatus",
    "SecReplaySession",
    "SecScheduledFundSelector",
    "SecSgmlFinancialProduction",
    "SecSgmlFinancialsRequest",
    "SecStatementParseError",
    "SecStatementRow",
    "SecStructuralQualityReport",
    "SecTransportEvidence",
    "SecUnavailableResult",
    "SecXbrlPackage",
    "SecXbrlPackageAvailability",
    "SecXbrlPackageComponents",
    "SecXbrlPackageFinancialProduction",
    "StatementType",
    "atomic_json",
    "canonical_hash",
    "canonical_json",
    "decode_sec_xbrl_package",
    "enrich_vintages",
    "ensure_edgar_available",
    "enumerate_receipts",
    "evaluate_sec_structural_quality",
    "extract_from_artifact",
    "historical_basenames",
    "historical_submission_url",
    "latest_completed_quarter",
    "load_sec_pit_bundle",
    "load_universe",
    "logical_table_hash",
    "parse_sec_date",
    "parse_statement_rows",
    "parse_submissions",
    "partition_identity",
    "produce_sec_financials_from_sgml",
    "produce_sec_financials_from_xbrl_package",
    "publish_directory",
    "qualify_sec_nport",
    "quarter_range",
    "read_member",
    "resolve_submissions",
    "rows_from_result",
    "select_exact_partitions",
    "select_sec_financial_versions",
    "select_sec_quality_findings",
    "serialize_sec_typed_rows_projection",
    "serialize_sec_xbrl_package",
    "store_immutable_payload",
    "validate_sec_url",
    "validate_tables",
    "validate_user_agent",
    "write_financials_partition",
    "write_partition",
    "write_sec_pit_bundle",
    "write_tables",
]
